const bootcampers = [
  { firstName: "Patrick", lastName: "Young" },
  { firstName: "Mark", lastName: "Gilliland" },
  { firstName: "Liz", lastName: "Kaufman" },
  { firstName: "Cheryl", lastName: "Asif" },
  { firstName: "Jodie", lastName: "Neville" },
  { firstName: "Tao", lastName: "Sharma" },
  { firstName: "Sam", lastName: "Webber" },
  { firstName: "Charles", lastName: "Baiden" },
  { firstName: "Mark", lastName: "Gilligan " },
  { firstName: "Helen", lastName: "Kent" },
  { firstName: "Alexa-Jane", lastName: "Berry" },
  { firstName: "Grace", lastName: "Barata" },
  { firstName: "Hannah", lastName: "Murphy" },
  { firstName: "James", lastName: "Greygoose" },
  { firstName: "Joshua", lastName: "Douglas-Smith" },
  { firstName: "Melanie", lastName: "Russon" },
  { firstName: "Murray", lastName: "Hoggett" },
  { firstName: "Olivia", lastName: "McLeod" },
  { firstName: "Ravinder", lastName: "Chahal" },
  { firstName: "Sam", lastName: "Dent" },
  { firstName: "Sarah", lastName: "Barkley" },
  { firstName: "Vinicius", lastName: "Pinhiero Porto" },
  { firstName: "Yasmin", lastName: "Ali" },
  { firstName: "Charlotte", lastName: "Mayne" }
];
